// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ajekfhspeyziomvcfmrg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFqZWtmaHNwZXl6aW9tdmNmbXJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNjU2MDUsImV4cCI6MjA3NDc0MTYwNX0.Q-DBNX1jZhJsCUpqlcBMkIDUol6qLRlREvsygF09_Bc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});